//! Async Runtime for Native Arth
//!
//! This module provides the runtime support for async/await in native-compiled
//! Arth code. It implements a simple cooperative task scheduler that manages
//! async tasks and their state machines.
//!
//! # Architecture
//!
//! The async runtime uses:
//! - **Tasks**: Units of async execution with state machine frames
//! - **Scheduler**: Cooperative round-robin task scheduler
//! - **Poll Functions**: State machine drivers generated by the compiler
//!
//! # Usage from LLVM IR
//!
//! ```llvm
//! ; Allocate async frame
//! %frame = call ptr @arth_rt_async_frame_alloc(i32 64)
//!
//! ; Spawn task with poll function
//! %task = call i64 @arth_rt_task_spawn_with_poll(ptr %frame, i64 %poll_fn_id)
//!
//! ; Await a task
//! %result = call i64 @arth_rt_await(i64 %task)
//! ```

use std::collections::HashMap;
use std::ptr;
use std::sync::Mutex;
use std::sync::atomic::{AtomicBool, AtomicI64, AtomicU32, Ordering};

// =============================================================================
// Constants and Types
// =============================================================================

/// Poll result values (must match IR PollResult enum)
pub mod poll_result {
    pub const READY: i64 = 0;
    pub const PENDING: i64 = 1;
    pub const CANCELLED: i64 = 2;
    pub const PANICKED: i64 = 3;
    pub const ERROR: i64 = 4;
}

/// Task state
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum TaskState {
    /// Task is ready to run
    Ready = 0,
    /// Task is waiting on another task
    Waiting = 1,
    /// Task has completed successfully
    Completed = 2,
    /// Task was cancelled
    Cancelled = 3,
    /// Task panicked
    Panicked = 4,
    /// Task threw an exception
    Error = 5,
}

// =============================================================================
// Async Frame
// =============================================================================

/// Async frame header layout (matches IR AsyncFrame layout)
/// Offset 0:   state: u32        - Current state ID
/// Offset 4:   (padding)
/// Offset 8:   result: i64       - Return value slot
/// Offset 16:  exception: i64    - Exception handle
/// Offset 24:  awaited: i64      - Currently awaited task handle
/// Offset 32+: user fields       - Parameters and cross-await locals
#[repr(C)]
pub struct AsyncFrameHeader {
    pub state: AtomicU32,
    pub _pad: u32,
    pub result: AtomicI64,
    pub exception: AtomicI64,
    pub awaited: AtomicI64,
}

impl AsyncFrameHeader {
    pub const STATE_OFFSET: u32 = 0;
    pub const RESULT_OFFSET: u32 = 8;
    pub const EXCEPTION_OFFSET: u32 = 16;
    pub const AWAITED_OFFSET: u32 = 24;
    pub const USER_FIELDS_START: u32 = 32;
}

// =============================================================================
// Task
// =============================================================================

/// A task represents an async computation
struct Task {
    /// Unique task handle
    #[allow(dead_code)]
    handle: i64,
    /// Pointer to the async frame
    frame_ptr: *mut u8,
    /// Poll function ID (hash of function name)
    poll_fn_id: i64,
    /// Current task state
    state: TaskState,
    /// Result value (when completed)
    result: i64,
    /// Exception value (when errored)
    exception: i64,
    /// Whether this task has been cancelled
    cancelled: AtomicBool,
}

unsafe impl Send for Task {}
unsafe impl Sync for Task {}

// =============================================================================
// Scheduler
// =============================================================================

/// Global task registry
struct TaskRegistry {
    tasks: HashMap<i64, Task>,
    next_handle: i64,
    /// Poll function registry (fn_id -> actual function pointer)
    poll_functions: HashMap<i64, PollFn>,
}

/// Type of poll function: (frame_ptr, task_handle) -> poll_result
type PollFn = unsafe extern "C" fn(*mut u8, i64) -> i64;

impl TaskRegistry {
    fn new() -> Self {
        Self {
            tasks: HashMap::new(),
            next_handle: 1,
            poll_functions: HashMap::new(),
        }
    }
}

static TASK_REGISTRY: Mutex<Option<TaskRegistry>> = Mutex::new(None);

/// Initialize the task registry
fn ensure_registry() {
    let mut guard = TASK_REGISTRY.lock().unwrap();
    if guard.is_none() {
        *guard = Some(TaskRegistry::new());
    }
}

fn with_registry<F, R>(f: F) -> R
where
    F: FnOnce(&mut TaskRegistry) -> R,
{
    ensure_registry();
    let mut guard = TASK_REGISTRY.lock().unwrap();
    f(guard.as_mut().unwrap())
}

// =============================================================================
// Frame Operations
// =============================================================================

/// Allocate an async frame on the heap
///
/// # Arguments
/// - `size`: Total size of the frame in bytes
///
/// # Returns
/// Pointer to the allocated frame
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_async_frame_alloc(size: u32) -> *mut u8 {
    unsafe {
        let layout = std::alloc::Layout::from_size_align_unchecked(size as usize, 8);
        let ptr = std::alloc::alloc_zeroed(layout);
        if ptr.is_null() {
            eprintln!("arth_rt_async_frame_alloc: allocation failed");
            std::process::abort();
        }
        ptr
    }
}

/// Free an async frame
///
/// # Arguments
/// - `frame_ptr`: Pointer to the frame to free
/// - `size`: Size of the frame in bytes
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_async_frame_free(frame_ptr: *mut u8, size: u32) {
    if frame_ptr.is_null() || size == 0 {
        return;
    }
    unsafe {
        let layout = std::alloc::Layout::from_size_align_unchecked(size as usize, 8);
        std::alloc::dealloc(frame_ptr, layout);
    }
}

/// Get the current state from an async frame
///
/// # Arguments
/// - `frame_ptr`: Pointer to the async frame
///
/// # Returns
/// Current state ID
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_async_frame_get_state(frame_ptr: *mut u8) -> i64 {
    if frame_ptr.is_null() {
        return 0;
    }
    unsafe {
        let header = frame_ptr as *const AsyncFrameHeader;
        (*header).state.load(Ordering::SeqCst) as i64
    }
}

/// Set the state in an async frame
///
/// # Arguments
/// - `frame_ptr`: Pointer to the async frame
/// - `state_id`: New state ID
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_async_frame_set_state(frame_ptr: *mut u8, state_id: u32) {
    if frame_ptr.is_null() {
        return;
    }
    unsafe {
        let header = frame_ptr as *mut AsyncFrameHeader;
        (*header).state.store(state_id, Ordering::SeqCst);
    }
}

/// Load a value from an async frame at the given offset
///
/// # Arguments
/// - `frame_ptr`: Pointer to the async frame
/// - `offset`: Byte offset within the frame
///
/// # Returns
/// The i64 value at the offset
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_async_frame_load(frame_ptr: *mut u8, offset: u32) -> i64 {
    if frame_ptr.is_null() {
        return 0;
    }
    unsafe {
        let ptr = frame_ptr.add(offset as usize) as *const i64;
        *ptr
    }
}

/// Store a value to an async frame at the given offset
///
/// # Arguments
/// - `frame_ptr`: Pointer to the async frame
/// - `offset`: Byte offset within the frame
/// - `value`: The i64 value to store
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_async_frame_store(frame_ptr: *mut u8, offset: u32, value: i64) {
    if frame_ptr.is_null() {
        return;
    }
    unsafe {
        let ptr = frame_ptr.add(offset as usize) as *mut i64;
        *ptr = value;
    }
}

// =============================================================================
// Task Operations
// =============================================================================

/// Spawn a new task with a poll function
///
/// # Arguments
/// - `frame_ptr`: Pointer to the async frame
/// - `poll_fn_id`: Hash ID of the poll function
///
/// # Returns
/// Task handle
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_task_spawn_with_poll(frame_ptr: *mut u8, poll_fn_id: i64) -> i64 {
    with_registry(|reg| {
        let handle = reg.next_handle;
        reg.next_handle += 1;

        let task = Task {
            handle,
            frame_ptr,
            poll_fn_id,
            state: TaskState::Ready,
            result: 0,
            exception: 0,
            cancelled: AtomicBool::new(false),
        };

        reg.tasks.insert(handle, task);
        handle
    })
}

/// Register a poll function
///
/// # Arguments
/// - `poll_fn_id`: Hash ID of the poll function
/// - `poll_fn`: Pointer to the poll function
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_register_poll_fn(poll_fn_id: i64, poll_fn: PollFn) {
    with_registry(|reg| {
        reg.poll_functions.insert(poll_fn_id, poll_fn);
    });
}

/// Check if a task has been cancelled
///
/// # Arguments
/// - `task_handle`: Handle of the task to check
///
/// # Returns
/// 1 if cancelled, 0 otherwise
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_task_is_cancelled(task_handle: i64) -> i64 {
    with_registry(|reg| {
        if let Some(task) = reg.tasks.get(&task_handle) {
            if task.cancelled.load(Ordering::SeqCst) {
                1
            } else {
                0
            }
        } else {
            0
        }
    })
}

/// Cancel a task
///
/// # Arguments
/// - `task_handle`: Handle of the task to cancel
///
/// # Returns
/// 0 on success, -1 if task not found
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_task_cancel(task_handle: i64) -> i64 {
    with_registry(|reg| {
        if let Some(task) = reg.tasks.get_mut(&task_handle) {
            task.cancelled.store(true, Ordering::SeqCst);
            task.state = TaskState::Cancelled;
            0
        } else {
            -1
        }
    })
}

/// Cooperatively yield execution to the scheduler.
///
/// # Returns
/// 0 on success
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_task_yield() -> i64 {
    std::thread::yield_now();
    0
}

/// Check whether the current task has been cancelled.
///
/// Note: Native async runtime currently has no ambient "current task" tracking
/// in this C ABI entrypoint, so this returns 0 by default.
///
/// # Returns
/// 1 if cancelled, 0 otherwise
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_task_check_cancelled() -> i64 {
    0
}

/// Check if an awaited task has an error
///
/// # Arguments
/// - `task_handle`: Handle of the awaited task
///
/// # Returns
/// 1 if task has error, 0 otherwise
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_task_has_error(task_handle: i64) -> i64 {
    with_registry(|reg| {
        if let Some(task) = reg.tasks.get(&task_handle) {
            if task.state == TaskState::Error || task.state == TaskState::Panicked {
                1
            } else {
                0
            }
        } else {
            0
        }
    })
}

/// Get the error from an awaited task
///
/// # Arguments
/// - `task_handle`: Handle of the awaited task
///
/// # Returns
/// Exception value, or 0 if no error
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_task_get_error(task_handle: i64) -> i64 {
    with_registry(|reg| {
        if let Some(task) = reg.tasks.get(&task_handle) {
            task.exception
        } else {
            0
        }
    })
}

/// Get the result from an awaited task
///
/// # Arguments
/// - `task_handle`: Handle of the awaited task
///
/// # Returns
/// Result value
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_task_get_result(task_handle: i64) -> i64 {
    with_registry(|reg| {
        if let Some(task) = reg.tasks.get(&task_handle) {
            task.result
        } else {
            0
        }
    })
}

/// Check if a task is completed (success or error)
///
/// # Arguments
/// - `task_handle`: Handle of the task to check
///
/// # Returns
/// 1 if completed, 0 otherwise
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_task_is_completed(task_handle: i64) -> i64 {
    with_registry(|reg| {
        if let Some(task) = reg.tasks.get(&task_handle) {
            match task.state {
                TaskState::Completed
                | TaskState::Error
                | TaskState::Panicked
                | TaskState::Cancelled => 1,
                _ => 0,
            }
        } else {
            1 // Non-existent task is considered completed
        }
    })
}

/// Create a CancelledError exception
///
/// # Arguments
/// - `task_handle`: Handle of the cancelled task (for context)
///
/// # Returns
/// Exception handle
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_create_cancelled_error(task_handle: i64) -> i64 {
    // Create a simple cancelled error marker
    // In a full implementation, this would create a proper exception object
    // For now, we use a magic value to indicate cancellation
    const CANCELLED_ERROR_MARKER: i64 = -0x43414E43454C4544; // "CANCELED" as negative
    CANCELLED_ERROR_MARKER ^ task_handle
}

/// Yield control to the scheduler
///
/// # Arguments
/// - `awaited_task`: Handle of the task being awaited
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_async_yield(awaited_task: i64) {
    // In a full implementation, this would:
    // 1. Save the current task's state
    // 2. Mark the current task as waiting on awaited_task
    // 3. Switch to the scheduler to run other tasks
    //
    // For now, we just yield the thread
    let _ = awaited_task;
    std::thread::yield_now();
}

/// Await a task (blocking until it completes)
///
/// # Arguments
/// - `task_handle`: Handle of the task to await
///
/// # Returns
/// The result of the task
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_await(task_handle: i64) -> i64 {
    // Poll the task until it completes
    loop {
        let (state, result, poll_fn, frame_ptr) = with_registry(|reg| {
            if let Some(task) = reg.tasks.get(&task_handle) {
                let poll_fn = reg.poll_functions.get(&task.poll_fn_id).copied();
                (task.state, task.result, poll_fn, task.frame_ptr)
            } else {
                (TaskState::Completed, 0, None, ptr::null_mut())
            }
        });

        match state {
            TaskState::Completed => return result,
            TaskState::Error | TaskState::Panicked | TaskState::Cancelled => {
                // Return the error/exception value
                return with_registry(|reg| {
                    reg.tasks
                        .get(&task_handle)
                        .map(|t| t.exception)
                        .unwrap_or(0)
                });
            }
            TaskState::Ready | TaskState::Waiting => {
                // Poll the task
                if let Some(poll_fn) = poll_fn {
                    let poll_result = unsafe { poll_fn(frame_ptr, task_handle) };

                    // Update task state based on poll result
                    with_registry(|reg| {
                        if let Some(task) = reg.tasks.get_mut(&task_handle) {
                            match poll_result {
                                poll_result::READY => {
                                    task.state = TaskState::Completed;
                                    // Load result from frame
                                    unsafe {
                                        if !task.frame_ptr.is_null() {
                                            let header = task.frame_ptr as *const AsyncFrameHeader;
                                            task.result = (*header).result.load(Ordering::SeqCst);
                                        }
                                    }
                                }
                                poll_result::PENDING => {
                                    task.state = TaskState::Waiting;
                                }
                                poll_result::CANCELLED => {
                                    task.state = TaskState::Cancelled;
                                }
                                poll_result::PANICKED => {
                                    task.state = TaskState::Panicked;
                                    // Load exception from frame
                                    unsafe {
                                        if !task.frame_ptr.is_null() {
                                            let header = task.frame_ptr as *const AsyncFrameHeader;
                                            task.exception =
                                                (*header).exception.load(Ordering::SeqCst);
                                        }
                                    }
                                }
                                poll_result::ERROR => {
                                    task.state = TaskState::Error;
                                    // Load exception from frame
                                    unsafe {
                                        if !task.frame_ptr.is_null() {
                                            let header = task.frame_ptr as *const AsyncFrameHeader;
                                            task.exception =
                                                (*header).exception.load(Ordering::SeqCst);
                                        }
                                    }
                                }
                                _ => {
                                    // Unknown poll result
                                    task.state = TaskState::Error;
                                }
                            }
                        }
                    });

                    // If still pending, yield to allow other work
                    if poll_result == poll_result::PENDING {
                        std::thread::yield_now();
                    }
                } else {
                    // No poll function registered - treat as completed
                    with_registry(|reg| {
                        if let Some(task) = reg.tasks.get_mut(&task_handle) {
                            task.state = TaskState::Completed;
                        }
                    });
                    return result;
                }
            }
        }
    }
}

/// Join a task (await its completion, propagating exceptions)
///
/// # Arguments
/// - `task_handle`: Handle of the task to join
///
/// # Returns
/// The result of the task (throws if task errored)
#[unsafe(no_mangle)]
pub extern "C" fn arth_rt_task_join(task_handle: i64) -> i64 {
    let result = arth_rt_await(task_handle);

    // Check if the task errored
    let has_error = arth_rt_task_has_error(task_handle);
    if has_error != 0 {
        // In a full implementation, we'd rethrow the exception here
        // For now, we just return the error value
        return arth_rt_task_get_error(task_handle);
    }

    result
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_frame_alloc_free() {
        let frame = arth_rt_async_frame_alloc(64);
        assert!(!frame.is_null());
        arth_rt_async_frame_free(frame, 64);
    }

    #[test]
    fn test_frame_state() {
        let frame = arth_rt_async_frame_alloc(64);

        // Initial state should be 0
        assert_eq!(arth_rt_async_frame_get_state(frame), 0);

        // Set state
        arth_rt_async_frame_set_state(frame, 5);
        assert_eq!(arth_rt_async_frame_get_state(frame), 5);

        arth_rt_async_frame_free(frame, 64);
    }

    #[test]
    fn test_frame_load_store() {
        let frame = arth_rt_async_frame_alloc(64);

        // Store a value at offset 32 (first user field)
        arth_rt_async_frame_store(frame, 32, 42);
        assert_eq!(arth_rt_async_frame_load(frame, 32), 42);

        // Store at offset 40
        arth_rt_async_frame_store(frame, 40, 123);
        assert_eq!(arth_rt_async_frame_load(frame, 40), 123);

        arth_rt_async_frame_free(frame, 64);
    }

    #[test]
    fn test_task_spawn() {
        let frame = arth_rt_async_frame_alloc(64);
        let handle = arth_rt_task_spawn_with_poll(frame, 12345);

        assert!(handle > 0);
        assert_eq!(arth_rt_task_is_cancelled(handle), 0);
        assert_eq!(arth_rt_task_is_completed(handle), 0);
    }

    #[test]
    fn test_task_cancel() {
        let frame = arth_rt_async_frame_alloc(64);
        let handle = arth_rt_task_spawn_with_poll(frame, 12345);

        assert_eq!(arth_rt_task_is_cancelled(handle), 0);

        arth_rt_task_cancel(handle);

        assert_eq!(arth_rt_task_is_cancelled(handle), 1);
    }

    #[test]
    fn test_task_yield() {
        assert_eq!(arth_rt_task_yield(), 0);
    }

    #[test]
    fn test_task_check_cancelled_default() {
        assert_eq!(arth_rt_task_check_cancelled(), 0);
    }

    #[test]
    fn test_cancelled_error() {
        let error = arth_rt_create_cancelled_error(42);
        assert_ne!(error, 0);
        assert_ne!(error, 42);
    }

    #[test]
    fn test_poll_result_values() {
        assert_eq!(poll_result::READY, 0);
        assert_eq!(poll_result::PENDING, 1);
        assert_eq!(poll_result::CANCELLED, 2);
        assert_eq!(poll_result::PANICKED, 3);
        assert_eq!(poll_result::ERROR, 4);
    }
}
